### ISSUE TITLE
Way to resume running after crash?

### ISSUE THREAD

**Issue by katieemelianova** [statbio/Sargasso#109]
Me again, sorry for bombarding you with issues! :)

I'm finding the pipeline super useful and easy to run so far, though (due to reasons on my end I suspect) the pipeline stalls at the end of the STAR mapping step, and I have to rerun a lot of it. Is there a way to specify pre-mapped BAM files or resume from a specific point? I tried to bodge it last night by creating a Make file and only rerunning from the sorting step (SORTED_READS) by deleting the previous steps from the Makefile but sambamba compained about the bam files not being sorted :/

Best,

Katie

**Comment by lweasel** [comment]
So I think you should indeed be able to run from a specific point, if the pipeline has stalled after the STAR mapping step. If that has happened, then if you go down into the Sargasso output directory, I would expect you would see some directories, such as "mapper_indexes", "raw_reads" and "mapped_reads". There should also be a Makefile (because underneath the hood the pipeline runs via this Makefile). 

If the pipeline has stalled before getting to the next step after read mapping (which is the read sorting step), then I would expect there not to be a "sorted_reads" directory, or a "filtered_reads" directory. If that is the case, then you should be able to just run "make" in the Sargasso output directory to resume the pipeline. I guess that it is also possible that one of the steps might have "partially" run - e.g. the "sorted_reads" directory might exist, but not include sorted BAM files for every sample. In that case, if you deleted the "sorted_reads" directory and ran "make", the pipeline should resume by created the "sorted_reads" directory and starting to sort the BAM files.

Does that make any sense?

**Comment by katieemelianova** [comment]
Ahhh yes I hadn't tried that - excellent that'll save me much faffing in the future and looks much more straightforward! Thanks very much! :)

**Comment by lweasel** [comment]
Great - let us know if you have any problems with that though of couse.
