### ISSUE TITLE
Deal with insertions and deletions wrt reference in CIGAR string

### ISSUE THREAD

**Issue by lweasel** [statbio/Sargasso#58]
It looks like these aren't recorded as mismatches in the NM tag. However, a mapping with an insertion or a deletion should be regarded as worse than one without.

**Comment by hxin** [comment]
* take a look first at the test samples, to get an idea how the cigar strings looks like

**Comment by hxin** [comment]
I implement a check within each filter so that if a hit contains any insertion/deletion, it will be discarded. However, the test results on the 'trap' data show that this change leads to an increase in the number of correct reads being rejected, as shown in the Figure. 

![cigarinsertiondeletion-primaryhit](https://user-images.githubusercontent.com/3407502/35447485-c0a1ee36-02af-11e8-80b3-cb96f4a9d0a7.png)
[cigarInsertionDeletion-primaryHit.txt](https://github.com/statbio/Sargasso/files/1668255/cigarInsertionDeletion-primaryHit.txt)
